{% set name = "suremco" %}
{% set version = "1.0.0rc1" %}
{% set sha256 = "dbdae5960776577aacdc3ce86e1b9e713760a1f4d0fbddac118bc2eab2021e0a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  #path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - numexpr
    - vispy
    - scipy
    - opencv
    - yaval
    - trackpy
test:
  imports:
    - suremco

about:
  home: https://github.com/modsim/suremco
  license: BSD-2-Clause
  license_family: BSD
  summary: 'Superresolution Emitter Counter'
  description: |
    Superresolution Emitter Counter
  doc_url: https://github.com/modsim/suremco
  dev_url: https://github.com/modsim/suremco

extra:
  recipe-maintainers:
    - csachs
