{% set name = "superresolution" %}
{% set version = "0.0.1.post1" %}
{% set sha256 = "" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #fn: {{ name }}-{{ version }}.tar.gz
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #sha256: {{ sha256 }}
  path: ..

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - numexpr
    - vispy
    - scipy
    - opencv
    - yaval
    - trackpy
test:
  imports:
    - superresolution

about:
  home: https://github.com/modsim/superresolution-bacterial-analysis-tool
  license: BSD-2-Clause
  license_family: BSD
  summary: 'Superresolution Analysis Software'
  description: |
    Superresolution Analysis Software
  doc_url: https://github.com/csachs/superresolution-bacterial-analysis-tool
  dev_url: https://github.com/csachs/superresolution-bacterial-analysis-tool

extra:
  recipe-maintainers:
    - csachs
